version: "3.8"
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        stdin_open: true
    
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
    
    database:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017:27017
        volumes:
            - database:/data/db

volumes:
    database:
