version: "3.8"
services:
    client:
        build:
            context: ../client
            dockerfile: ../docker/Dockerfile.client
        ports:
            - "3000:3000"
        stdin_open: true
    
    server:
        depends_on: 
            - mongo
        build:
            context: ../server
            dockerfile: ../docker/Dockerfile.server
        environment: 
            PORT: 5000
            MONGODB_URI: mongodb://root:password@mongo:27017/cassettenet
        ports:
            - "5000:5000"

    mongo:
        build: ./mongo
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: cassettenet
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
            - ./mongo/init-db.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    
    # GUI interface for mongo
    mongo-express:
        depends_on: 
            - mongo
        image: mongo-express
        environment: 
            ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: mongo
        ports: 
            - 8081:8081

volumes:
    mongo:
